import { Kysely, sql } from 'kysely'

export async function up(db: Kysely<any>): Promise<void> {
  await sql`CREATE EXTENSION IF NOT EXISTS pgcrypto`.execute(db)

  await db.schema.createTable('users')
    .addColumn('id', 'uuid', c => c.primaryKey().defaultTo(sql`gen_random_uuid()`))
    .addColumn('email', 'text', c => c.notNull().unique())
    .addColumn('display_name', 'text', c => c.notNull())
    .addColumn('role', 'text', c => c.notNull())
    .addColumn('password_hash', 'text', c => c.notNull())
    .addColumn('created_at', 'timestamptz', c => c.notNull().defaultTo(sql`now()`))
    .addColumn('disabled_at', 'timestamptz')
    .execute()

  await db.schema.createTable('teams')
    .addColumn('id', 'uuid', c => c.primaryKey().defaultTo(sql`gen_random_uuid()`))
    .addColumn('name', 'text', c => c.notNull())
    .addColumn('created_at', 'timestamptz', c => c.notNull().defaultTo(sql`now()`))
    .execute()

  await db.schema.createTable('team_members')
    .addColumn('team_id', 'uuid', c => c.notNull().references('teams.id').onDelete('cascade'))
    .addColumn('user_id', 'uuid', c => c.notNull().references('users.id').onDelete('cascade'))
    .addColumn('is_lead', 'boolean', c => c.notNull().defaultTo(false))
    .addPrimaryKeyConstraint('team_members_pk', ['team_id', 'user_id'])
    .execute()

  await db.schema.createTable('accounts')
    .addColumn('id', 'uuid', c => c.primaryKey().defaultTo(sql`gen_random_uuid()`))
    .addColumn('platform', 'text', c => c.notNull())
    .addColumn('owner_user_id', 'uuid', c => c.notNull().references('users.id'))
    .addColumn('team_id', 'uuid', c => c.references('teams.id'))
    .addColumn('display_name', 'text', c => c.notNull())
    .addColumn('status', 'text', c => c.notNull().defaultTo('pending_auth'))
    .addColumn('credentials_ref', 'text')
    .addColumn('linked_at', 'timestamptz')
    .addColumn('history_available_from', 'timestamptz')
    .addColumn('created_at', 'timestamptz', c => c.notNull().defaultTo(sql`now()`))
    .execute()

  await db.schema.createTable('conversations')
    .addColumn('id', 'uuid', c => c.primaryKey().defaultTo(sql`gen_random_uuid()`))
    .addColumn('account_id', 'uuid', c => c.notNull().references('accounts.id').onDelete('cascade'))
    .addColumn('platform_conversation_id', 'text', c => c.notNull())
    .addColumn('contact_external_id', 'text', c => c.notNull())
    .addColumn('contact_display_name', 'text')
    .addColumn('last_message_at', 'timestamptz')
    .addUniqueConstraint('conversations_account_platform_uq', ['account_id', 'platform_conversation_id'])
    .execute()

  await db.schema.createTable('messages')
    .addColumn('id', 'uuid', c => c.primaryKey().defaultTo(sql`gen_random_uuid()`))
    .addColumn('conversation_id', 'uuid', c => c.notNull().references('conversations.id').onDelete('cascade'))
    .addColumn('account_id', 'uuid', c => c.notNull().references('accounts.id').onDelete('cascade'))
    .addColumn('platform', 'text', c => c.notNull())
    .addColumn('platform_message_id', 'text', c => c.notNull())
    .addColumn('direction', 'text', c => c.notNull())
    .addColumn('sender_external_id', 'text', c => c.notNull())
    .addColumn('body', 'text', c => c.notNull())
    .addColumn('body_lang', 'text')
    .addColumn('media_refs', 'jsonb', c => c.notNull().defaultTo(sql`'[]'::jsonb`))
    .addColumn('sent_at', 'timestamptz', c => c.notNull())
    .addColumn('ingested_at', 'timestamptz', c => c.notNull().defaultTo(sql`now()`))
    .addColumn('raw', 'jsonb', c => c.notNull().defaultTo(sql`'{}'::jsonb`))
    .addUniqueConstraint('messages_account_platform_msg_uq', ['account_id', 'platform_message_id'])
    .execute()

  await db.schema.createIndex('messages_conversation_sent_idx')
    .on('messages').columns(['conversation_id', 'sent_at']).execute()

  await db.schema.createTable('message_translations')
    .addColumn('message_id', 'uuid', c => c.notNull().references('messages.id').onDelete('cascade'))
    .addColumn('target_lang', 'text', c => c.notNull())
    .addColumn('provider', 'text', c => c.notNull())
    .addColumn('translated_text', 'text', c => c.notNull())
    .addColumn('created_at', 'timestamptz', c => c.notNull().defaultTo(sql`now()`))
    .addPrimaryKeyConstraint('message_translations_pk', ['message_id', 'target_lang'])
    .execute()
}

export async function down(db: Kysely<any>): Promise<void> {
  await db.schema.dropTable('message_translations').ifExists().execute()
  await db.schema.dropTable('messages').ifExists().execute()
  await db.schema.dropTable('conversations').ifExists().execute()
  await db.schema.dropTable('accounts').ifExists().execute()
  await db.schema.dropTable('team_members').ifExists().execute()
  await db.schema.dropTable('teams').ifExists().execute()
  await db.schema.dropTable('users').ifExists().execute()
}
